services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:

  test:
    image: python:3.6
    commands:
      - bash scripts/tcp-port-wait.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - bash scripts/run-tests.sh --ci
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "db"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      JWT_ISSUER: "crmservice"
      JWT_PRIVATE_KEY_RSA_CRMSERVICE: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOgIBAAJBAMtUe741n497BS4syFvey617qA+b4DQSyHj4xE0ZH5qRuk/A42i5
        zUJidSkFs1Wvq9ShOamST1vrmHriBrYYu7MCAwEAAQJBAI2hUXiSvYwh8t/RDdcA
        f/tdkRkeSLO9CatKDOJvR5ZQAL5+7iNHTMGOC2FCU3WKSdlEo/xW3kD6omYbIWPk
        hXECIQD58w4Zl3FSaoWBhBmmyJF08cOQP2Z8amewd70LV0LNlQIhANBAhrTxnDG2
        KprAffkxjcrV/6ZWC5kGqckTNUUhf0InAiBbosNpmH8gYxM9L4wj/GZvhG9ZRBUz
        yeLn7I4vSTehnQIgJEaZMHvF0YMB+OL/DqFrKaINXlQuwQFAIh6OcPRczpECICpM
        q/qlwzGMpOD6blcWDUqgS6HXpS73To/F8RE56FP+
        -----END RSA PRIVATE KEY-----
      SEARCH_SERVICE_URL: "http://searchservice.local:8001"
      SECRET_KEY: "nothing"
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/crm_service
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      status: [success]

  prebuild-docker-static-image:
    image: python:3.6
    commands:
      - bash scripts/run-collectstatic.sh
    when:
      event: [tag]
      status: [success]

  build-docker-static-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec/crm_service_static
    dockerfile: Dockerfile.nginx
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]
